### ISSUE TITLE
I love this get_average_sentence_length function

### ISSUE THREAD

**Issue by jmcrey** [tabernarious/murder-mystery#1]
https://github.com/tabernarious/murder-mystery/blob/6066657313790f0ea5f63af795ce1cbda52fad6f/Murder%2BMystery.py#L3-L30

I love this implementation of the `get_average_sentence_length` function. It is super clever. For me, a highlight is that you separated out the functionality of counting sentences into a different function. This is a true emulation of the "One function, One thing" mantra programmers strive to obtain. Fantastic job!

**Comment by tabernarious** [comment]
Thank you! When I got to the very end of this project and saw how close Myrtle was I went back through and reviewed all of my code to be sure I wasn't off on something. I looked at the hint for this first section and was quite surprised at the idea of capturing each sentence, counting the words, then calculating an average. If there had been some other need to analyze individual sentences later in the project, then that approach would have saved the time building that code.
