### ISSUE TITLE
Clever use of Regex to complete the prepare_text function

### ISSUE THREAD

**Issue by jmcrey** [tabernarious/murder-mystery#2]
https://github.com/tabernarious/murder-mystery/blob/6066657313790f0ea5f63af795ce1cbda52fad6f/Murder%2BMystery.py#L32-L41

Really nice job with this! It was very clever to use regex to strip out all extraneous characters. To be honest, this might even be more memory efficient than our solution (which utilizes `join()` and a list comprehension). In any case, really nice job! Great use of regex!

**Comment by tabernarious** [comment]
Cheers! regex *is* awesome--it's something I have used extensively in scripting (bash, sed, awk, Notepad++, tcl, etc.) and it often comes to mind for complex search/replace scenarios. I have often been warned that regex is more resource-intensive than other built-in functions, but that does depend on the available built-in functions of each language and the complexity of the required search/replace.

**Comment by jmcrey** [comment]
@tabernarious Okay, it's true that regex is more resource-intensive; but, I _believe_ that is only with processing power. In terms of memory efficiency, I _believe_ it is often the case that regex is less memory intensive than other alternatives simply because it is tampering with the original memory space instead of creating separate copies throughout iteration. Obviously, this is not universally true and it highly depends on the language; but, I feel like it's generally true (especially in Python where memory doesn't get released back to the OS until the program has exited).

 But, you're right, it does depending on the built-in functions and the complexity of the search. For something like C or bash, you bet regex is one of the best, especially for complex searches. But, for "higher" languages (or even query languages like SQL), it is often the case that there are better alternatives to completing the operations that we desire. In any case, I still like the use of regex in this function.
