### ISSUE TITLE
Great job calculation percent different! Just try to format the code a bit more for readability

### ISSUE THREAD

**Issue by jmcrey** [tabernarious/murder-mystery#3]
https://github.com/tabernarious/murder-mystery/blob/6066657313790f0ea5f63af795ce1cbda52fad6f/Murder%2BMystery.py#L107-L113

These implementations are perfect for calculating the percent different between two numbers. I also like how the parameter is switch from expecting a number to expecting the whole sample -- in my opinion, this is how it should be done because then it spurs more uniformity in parameter passing; but, I digress. 

My one issue is that it can be a bit cumbersome to read since the lines are so long. According to PEP8, I believe our lines should only be about 120 characters long -- so, for this function, it might be better to split it out into two different parts, or just utilize spacing in our return. Basically, we can just create a `numerator` and `denominator` variable and then just return `numerator / denominator`. Or, we can just visually separate our return:

```
return abs(
            sample1.average_sentence_length_by_characters -
            sample2.average_sentence_length_by_characters
       ) \ (
             (sample1.average_sentence_length_by_characters + 
              sample2.average_sentence_length_by_characters)
             / 2
            )
```

Personally, I like the visual look of the `numerator` and `denominator`, but this is just a matter of preference. Either way, great job with these functions!

**Comment by tabernarious** [comment]
I completely agree. My long variable names were particularly troublesome. I like your suggestion for `numerator` and `denominator`, which I believe would look like this:

```
def percent_difference(sample1, sample2):
    # Calculate and return: abs(v1 - v2) / ((v1 + v2)/2)
    numerator = abs(sample1.average_sentence_length - sample2.average_sentence_length)
    denominator = (sample1.average_sentence_length + sample2.average_sentence_length) / 2
    return numerator / denominator
```

I also realized I could have just done this:

```
def percent_difference(sample1, sample2): 
    v1 = sample1.average_sentence_length
    v2 = sample2.average_sentence_length

    # Calculate and return: abs(v1 - v2) / ((v1 + v2)/2)
    return abs(v1 - v2) / ((v1 + v2)/2)
```

**Comment by jmcrey** [comment]
Both of those are much more cleanly formatted and work equally well! I actually really like the look of the second version -- it keeps the calculation in one small, readable line, and it separates out variable declaration. But, again, either way is perfectly fine. Any programmer would have no trouble reading either. Great job!
