### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [tabernarious/murder-mystery#4]
### Criteria 1: Valid Python Code
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_ Code ran without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_ First of all, these functions were brilliant, Each of them was implemented with such detail and finesse. Plus, they all followed Python's best practices, made great use of Python's built-in features, and all of the functions were called appropriately. Moreover, the code contained detailed comments inside its functions, which aided the readers in interpreting the code base. Great job with implementation!
 
### Criteria 3: Software Architecture
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_ Code is separated into distinct classes and functions, each of which are invoked for their own purpose. A highlight was the `get_average_sentence_length`, which separated the calculation of the number of sentences into its own function. Absolutely marvelous job!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_ Code uses language features appropriately; if a task can be solved with a Python language feature, it is. For me, this is especially true in the `prepare_text` function, where you made fantastic use of regex to complete the task. One thing I did want to point out is that we could have used the `get` function instead of the `in` operator in our functions `frequency_comparison` and `build_frequency_table`. The `get` function returns the value of the specified dictionary key; if the key specified does not exist, then it returns None. This is super useful because it is efficient and it handles the `KeyError` in case the key doesn't already exist. Plus, on average, the `get` function performs a bit better than the `in` operator. So, it is definitely something to consider, but, honestly, either is completely fine.

### Criteria 5: Produces Accurate Output
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_ Code output is properly formatted and accurate. I especially liked the analysis at the end which declared a murderer, but called the case not obvious. Great interpretation of the returned values!
 
### Overall Score: **20/20**

Fantastic job with this project. Each function was implemented correctly and cleverly; the code followed Python's best practices; the output was correct and formatted nicely; and (an added bonus) the code contained detailed comments, which helped to display a true understanding of the code presented. Also, I love the analysis at the end, where a murderer is presumed but not definitive. 

Superb job with this project!

**Comment by tabernarious** [comment]
I really appreciate your detailed review. I'm excited that this all went so well!! And thanks for the tip/reminder about `get` instead of `in`.

Is this what you're referring to? Or is there more I can do?

(I did consolidate `frequency_comparison()` using `min()` and `max()` which I just found!)

```
def build_frequency_table(corpus):
    frequency_table = {}
    
    # Check each element of corpus for existence in frequency_table. Add or increment the element's value.
    for element in corpus:
        if frequency_table.get(element):
            frequency_table[element] += 1
        else:
            frequency_table[element] = 1
    
    return frequency_table

def frequency_comparison(table1, table2):
    # The number of appearances of all unique ngrams across both table1 and table2
    appearances = 0

    # The number of appearances of mutual ngrams bewtween table1 and table2
    mutual_appearances = 0

    # Iterate through table1's keys, check if the key exists in table2.
    #   For mutual keys add the smaller value to mutual_appearances, and add the larger value to appearances.
    #   For non-mutual keys, add the table1 value to appearances.
    # Then iterate through table2's keys, check if the key exists in table1.
    #   Ignore mutual keys (these have already been accounted for)
    #   For non-mutual keys, add the table2 value to appearances.
    for ngram in table1:
        if table2.get(ngram):
            mutual_appearances += min(table1[ngram], table2[ngram])
            appearances += max(table1[ngram], table2[ngram])
        else:
            appearances += table1[ngram]
    for ngram in table2.keys():
        if not table1.get(ngram):
            appearances += table2[ngram]

    # Return the frequency comparison
    return mutual_appearances / appearances
```

**Comment by jmcrey** [comment]
Yes, that's actually exactly what I was referring to. Also, good consolidation on the `frequency_comparison` function. In a way, using the `min` and `max` functions actually make this function more readable simply because there are less lines to read and it makes the distinction between addition clear. 

But (just for your reference more than anything else) I wanted to note that we can actually store the return of the `get` function and use that value multiple times throughout our iteration. So, perhaps, we could have done this for `frequency_comparison`:

```
for ngram in table1:
        v1 = table1.get(ngram)
        v2 = table2.get(ngram)
        if v2:
            mutual_appearances += min(v1, v2)
            appearances += max(v1, v2)
        else:
            appearances += v1
    for ngram in table2.keys():
        if not table1.get(ngram):
            appearances += table2[ngram]
```

Notice that with declaring `v1` and `v2` at the top, we don't have to worry about accessing the value in the dictionary every time we need it. 

Side note: In this case, that doesn't make much of a difference because accessing a key-value in a dictionary is linear time; but, nonetheless, this type of nomenclature might help for a later purpose. 

Hope this helps!

**Comment by tabernarious** [comment]
Excellent. I did think about creating variables like that but it seemed a minimal advantage resource-wise. I'll continue to keep in mind the overall readability and ease of expansion/re-use as important factors. Cheers!
